version: '2'
services:
    adminpanel-app:
        image: adminpanel
        external_links:
            - adminpanel-postgresql:postgresql
            - adminpanel-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/adminPanel
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    adminpanel-postgresql:
        extends:
            file: postgresql.yml
            service: adminpanel-postgresql
    adminpanel-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: adminpanel-elasticsearch
